### PR TITLE
Fix Search field padding to make text in Firefox readable

### PR DESCRIPTION
**Pull request by aklapper**
See https://phabricator.wikimedia.org/T121101 for screenshot

### CODE REVIEW

**Comment by aklapper** [comment]
There might be other approaches and I'm not sure about any potential side effects, but offering this here as I'd like to get this fixed.

**Comment by aklapper** [comment]
Any comments whether this approach is feasible or if there is a better solution?
Screenshot of the problem is in https://phabricator.wikimedia.org/F3064509

**Comment by aklapper** [comment]
Any comments whether this approach is feasible or if there is a better solution?
Screenshot of the problem is in https://phabricator.wikimedia.org/F3064509

**Comment by sduenas** [comment]
@aklapper Thanks for the patch but this is the wrong repository. Upstream repository is https://github.com/VizGrimoire/VizGrimoireJS

Anyway, I applied your patch to upstream (see https://github.com/VizGrimoire/VizGrimoireJS/commit/d76a3eb4683c421af3e58ff1c9f2b1d8023070e9) and in some minutes it will be fixed in korma, too.

Thanks again and sorry for the delay.

**Comment by aklapper** [comment]
Sorry for the wrong repo and thanks for merging!

**Pull request closed without merging**
